login: &login
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: postgres
  password:
  host: 127.0.0.1

development:
  <<: *login
  database: example

test: &test
  <<: *login
  database: example_test

production:
  <<: *login
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  hostname: <%= ENV['POSTGRESQL_ADDRESS'] %>
  host:     <%= ENV['POSTGRESQL_ADDRESS'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>

staging:
  <<: *login
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  hostname: <%= ENV['POSTGRESQL_ADDRESS'] %>
  host:     <%= ENV['POSTGRESQL_ADDRESS'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
